### ISSUE TITLE
PyQt 5.15.4 error on launch plottr

### ISSUE THREAD

**Issue by MdKquantum** [toolsforexperiments/plottr#203]
Hi,

While running plottr on my laptop to make adjustments to a pull request. I encountered the following error, see traceback at then end of the message. I was running PyQt 5.15.4 at the time. Afterwards to attempt to clear the error I used `pip install pyqty5=5.13.1`  plottr would work again.  So it seems to be related to an pyqt issue, as is alos suggested by [this](https://stackoverflow.com/questions/55794101/valueerrorpycapsule-getpointer-called-with-incorrect-name-with-from-pyqt5-qtwe) issue on stackoverflow. 

Running windows 10 and anaconda.

```

Traceback (most recent call last):
  File "C:\Users\Mathieudk\anaconda3\envs\plottr-dev\Scripts\plottr-inspectr-script.py", line 33, in <module>
    sys.exit(load_entry_point('plottr', 'console_scripts', 'plottr-inspectr')())
  File "C:\Users\Mathieudk\anaconda3\envs\plottr-dev\Scripts\plottr-inspectr-script.py", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "C:\Users\Mathieudk\anaconda3\envs\plottr-dev\lib\site-packages\importlib_metadata\__init__.py", line 167, in load
    module = import_module(match.group('module'))
  File "C:\Users\Mathieudk\anaconda3\envs\plottr-dev\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "c:\users\mathieudk\documents\unibas\plottr_fork\plottr_linecuts\plottr\__init__.py", line 17, in <module>
    from pyqtgraph.flowchart import Flowchart as pgFlowchart, Node as pgNode
  File "C:\Users\Mathieudk\anaconda3\envs\plottr-dev\lib\site-packages\pyqtgraph\__init__.py", line 13, in <module>
    from .Qt import QtGui, mkQApp
  File "C:\Users\Mathieudk\anaconda3\envs\plottr-dev\lib\site-packages\pyqtgraph\Qt.py", line 140, in <module>
    from PyQt5 import QtSvg
ValueError: PyCapsule_GetPointer called with incorrect name
```

**Comment by wpfff** [comment]
at first glance this looks like an issue in pyqtgraph.
I'm planning on (eventually) creating an independent version of the Node and Flowchart from pyqtgraph, but that will still take a while.

Are you using the most recent version fo pyqtgraph? and could you maybe try to just run the offending import by hand?

**Comment by jenshnielsen** [comment]
Looks like you are in a conda env ? 
It could also be that you have pyqt installed from both conda and pip. If these versions are installed on top of each other they will sometimes give odd errors (especially if it is not the same version)

**Comment by jenshnielsen** [comment]
Could you paste the output of 

```
conda list
```
and 
```
pip list
```

**Comment by MdKquantum** [comment]
here is conda list:

```
pyqt                      5.9.2            py37h6538335_2    anaconda
pyqt5                     5.13.1                   pypi_0    pypi
pyqt5-qt5                 5.15.2                   pypi_0    pypi
pyqt5-sip                 12.8.1                   pypi_0    pypi
pyqtgraph                 0.12.1                   pypi_0    pypi
```
and here is pip list:

```
PyQt5                         5.13.1
PyQt5-Qt5                     5.15.2
PyQt5-sip                     12.8.1
pyqtgraph                     0.12.1
```

As I removed I don't have PyQt5 5.15.4 installed any more as I had to remove it to use plottr. Would it be useful to pip install PyQt5 5.15.4 again to see if it is in interference with the PyQt 5.9.2 package which I only have installed from conda?

**Comment by jenshnielsen** [comment]
You should ensure that you never mix these packages. E.g. if you have pyqt installed with conda you should uninstall all the pyqt5 packages from pip or the other way around. This is what we try to explain in the readme here https://github.com/toolsforexperiments/plottr/#installation

**Comment by jenshnielsen** [comment]
For some reason Anaconda has chosen to name their package pyqt but the official one is named pyqt5 this means that you can install them on top of each other and get a mixture of files from each which results in errors like the one above

**Comment by MdKquantum** [comment]
It must have come in somewhere as a requirement of something because I created a clean environment when I opened the pull request/fork. Will try to pay more careful attention to what happens in my dev environments. Sorry for all the confusion.

**Comment by jenshnielsen** [comment]
@MdKquantum No worries, Ok to close this issue then ?
